/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scrabble.punkty;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patryk
 */
public class scrabble_punkty extends javax.swing.JFrame {

    int punkty, mnoznik, gracz = 1, gracze = 2, tura = 0, premia_slowna;
    char litera;
    String slowo;
    String premki;
    boolean[] literowka = new boolean[15];

    /**
     * Creates new form scrabble_punkty
     */
    public scrabble_punkty() {
        initComponents();
        int szer = Toolkit.getDefaultToolkit().getScreenSize().width;
        int wys = Toolkit.getDefaultToolkit().getScreenSize().height;
        int szerRamki = this.getSize().width;
        int wysRamki = this.getSize().height;
        this.setLocation((szer - szerRamki) / 2, (wys - wysRamki) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        dodawanieG = new javax.swing.JButton();
        usuwanieG = new javax.swing.JButton();
        piedziesiatka = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();

        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox8.setText("7");
        jCheckBox8.setToolTipText("");

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox10.setText("7");
        jCheckBox10.setToolTipText("");

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox13.setText("10");
        jCheckBox13.setToolTipText("");

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox15.setText("11");
        jCheckBox15.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setSelectionColor(new java.awt.Color(0, 153, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("ZLICZ SŁOWO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("LICZBA GRACZY");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("premie literowe");
        jLabel3.setToolTipText("");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton1.setText("PREMIA SŁOWNA X2");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton2.setText("PREMIA SŁOWNA X3");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton3.setText("x2");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton4.setText("x3");

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCheckBox20.setText("2 premie słowne");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("...");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("litery z premią");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("...");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("...");

        jButton2.setText("SPRAWDŹ SŁOWO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, "XXX",  new Integer(0), "XXX",  new Integer(0)},
                {"Suma Punktów",  new Integer(0), "Suma Punktów",  new Integer(0), "Suma Punktów",  new Integer(0), "Suma Punktów",  new Integer(0)}
            },
            new String [] {
                "Słowo G1", "Punkty za słowo: G1", "Słowo G2", "Punkty za słowo: G2", "Słowo G3", "Punkty za słowo: G3", "Słowo G4", "Punkty za słowo: G4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("ZAPISZ SŁOWO");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dodawanieG.setText("Dodaj Gracza");
        dodawanieG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodawanieGActionPerformed(evt);
            }
        });

        usuwanieG.setText("Usuń Gracza");
        usuwanieG.setEnabled(false);
        usuwanieG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuwanieGActionPerformed(evt);
            }
        });

        piedziesiatka.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        piedziesiatka.setText("Wykorzystano wszystkie litery");

        jButton4.setText("KONIEC");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jCheckBox20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButton3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButton4))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(usuwanieG, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dodawanieG, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(203, 203, 203)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel6))))
                        .addGap(75, 76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(454, 454, 454)
                        .addComponent(piedziesiatka)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuwanieG)
                            .addComponent(dodawanieG)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(piedziesiatka)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuwanieGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuwanieGActionPerformed
        jTable1.setValueAt("XXX", 0, gracze * 2 - 2);
        jTable1.setValueAt(0, 0, gracze * 2 - 1);
        gracze--;
        if (gracze == 2) {
            usuwanieG.setEnabled(false);
        }
        if (gracze < 4) {
            dodawanieG.setEnabled(true);
        }
        jLabel2.setText(String.valueOf(gracze));
    }//GEN-LAST:event_usuwanieGActionPerformed

    private void dodawanieGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodawanieGActionPerformed
        gracze++;
        if (gracze == 4) {
            dodawanieG.setEnabled(false);
        }
        if (gracze > 2) {
            usuwanieG.setEnabled(true);
        }
        jTable1.setValueAt("", 0, gracze * 2 - 2);
        jTable1.setValueAt(0, 0, gracze * 2 - 1);
        jLabel2.setText(String.valueOf(gracze));
    }//GEN-LAST:event_dodawanieGActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        premki = "";
        punkty = 0;
        slowo = jTextField1.getText();
        String pomoc = slowo;
        jLabel4.setText((String.valueOf(slowo)).toUpperCase());

        jLabel4.setText(slowo);
        
        for (int i = 0; i < slowo.length(); i++) {
            if (jRadioButton3.isSelected() == true) {
                mnoznik = 2;
            } else {
                if (jRadioButton4.isSelected() == true) {
                    mnoznik = 3;
                } else {
                    mnoznik = 1;
                }
            }
            litera = slowo.charAt(i);
            System.out.println(litera);
            System.out.println(i);
            if (mnoznik != 1) {
                jLabel7.setText(String.valueOf("x" + mnoznik));
            } else {
                jLabel7.setText(String.valueOf("..."));
            }
            switch (litera) {
                case 'A':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ą':
                punkty = punkty + 5 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'B':
                punkty = punkty + 3 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'C':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ć':
                punkty = punkty + 6 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'D':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'E':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ę':
                punkty = punkty + 5 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'F':
                punkty = punkty + 5 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'G':
                punkty = punkty + 3 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'H':
                punkty = punkty + 3 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'I':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'J':
                punkty = punkty + 3 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'K':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'L':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ł':
                punkty = punkty + 3 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'M':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'N':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ń':
                punkty = punkty + 7 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'O':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ó':
                punkty = punkty + 5 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'P':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'R':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'S':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ś':
                punkty = punkty + 5 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'T':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'U':
                punkty = punkty + 3 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'W':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Y':
                punkty = punkty + 2 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Z':
                punkty = punkty + 1 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ź':
                punkty = punkty + 9 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'Ż':
                punkty = punkty + 5 * mnoznik;
                premki = new StringBuilder(premki).append(litera).append(" ,").toString();
                break;
                case 'a':
                punkty = punkty + 1;
                break;
                case 'ą':
                punkty = punkty + 5;
                break;
                case 'b':
                punkty = punkty + 3;
                break;
                case 'c':
                punkty = punkty + 2;
                break;
                case 'ć':
                punkty = punkty + 6;
                break;
                case 'd':
                punkty = punkty + 2;
                break;
                case 'e':
                punkty = punkty + 1;
                break;
                case 'ę':
                punkty = punkty + 5;
                break;
                case 'f':
                punkty = punkty + 5;
                break;
                case 'g':
                punkty = punkty + 3;
                break;
                case 'h':
                punkty = punkty + 3;
                break;
                case 'i':
                punkty = punkty + 1;
                break;
                case 'j':
                punkty = punkty + 3;
                break;
                case 'k':
                punkty = punkty + 2;
                break;
                case 'l':
                punkty = punkty + 2;
                break;
                case 'ł':
                punkty = punkty + 3;
                break;
                case 'm':
                punkty = punkty + 2;
                break;
                case 'n':
                punkty = punkty + 1;
                break;
                case 'ń':
                punkty = punkty + 7;
                break;
                case 'o':
                punkty = punkty + 1;
                break;
                case 'ó':
                punkty = punkty + 5;
                break;
                case 'p':
                punkty = punkty + 2;
                break;
                case 'r':
                punkty = punkty + 1;
                break;
                case 's':
                punkty = punkty + 1;
                break;
                case 'ś':
                punkty = punkty + 5;
                break;
                case 't':
                punkty = punkty + 2;
                break;
                case 'u':
                punkty = punkty + 3;
                break;
                case 'w':
                punkty = punkty + 1;
                break;
                case 'y':
                punkty = punkty + 2;
                break;
                case 'z':
                punkty = punkty + 1;
                break;
                case 'ź':
                punkty = punkty + 9;
                break;
                case 'ż':
                punkty = punkty + 5;
                break;
            }
        }
        if(jRadioButton1.isSelected() == true||jRadioButton2.isSelected() == true){
        if (jRadioButton1.isSelected() == true) {
            punkty = punkty * 2;
            premia_slowna = 2;
            if (jCheckBox20.isSelected() == true) {
                punkty = punkty * 2;
                premia_slowna = 4;
            }
        }
        if (jRadioButton2.isSelected() == true) {
            punkty = punkty * 3;
            premia_slowna = 3;
            if (jCheckBox20.isSelected() == true) {
                punkty = punkty * 3;
                premia_slowna = 9;
            }
        }
        }else{
            premia_slowna = 1;
        }
        jTextField1.setText("");
        if (mnoznik != 1) {
            jLabel6.setText(premki);
        } else {
            jLabel6.setText("...");
        }
        switch (premia_slowna) {
            case 2:
            pomoc.concat("x2");
            break;
            case 4:
            pomoc.concat("x2x2");
            break;
            case 3:
            pomoc.concat("x3");
            break;
            case 9:
            pomoc.concat("x3x3");
            break;
        }
        jLabel4.setText(pomoc);
        jLabel1.setText("PUNKTY ZA SŁOWO:");
        buttonGroup1.clearSelection();
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        buttonGroup2.clearSelection();
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jCheckBox20.setSelected(false);
        jLabel2.setText(String.valueOf(punkty));
        jButton3.setEnabled(true);
        if("".equals(slowo)){
            jLabel2.setText("Brak słowa");
            jLabel6.setText("...");
            jLabel7.setText("...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dodawanieG.setEnabled(false);
        usuwanieG.setEnabled(false);
        if("Brak słowa".equals(jLabel2.getText())){
            slowo="?";
        }
        if (piedziesiatka.isSelected() == true) {
            punkty = punkty + 50;
        }
        
        switch(mnoznik){
            case 2:
            slowo = slowo.concat("(Lx2)");
                    break;
                    case 3:
            slowo = slowo.concat("(Lx3)");
                    break;
        }
        jTable1.setValueAt(slowo, tura, gracz * 2 - 2);
        switch (premia_slowna) {
            case 2:
            slowo = slowo.concat("(Sx2)");
            System.out.println(slowo);
            break;
            case 4:
            slowo = slowo.concat("(Sx2x2)");
            System.out.println(slowo);
            break;
            case 3:
            slowo = slowo.concat("(Sx3)");
            System.out.println(slowo);
            break;
            case 9:
            slowo = slowo.concat("(Sx3x3)");
            System.out.println(slowo);
            break;
        }
        jTable1.setValueAt(slowo, tura, gracz * 2 - 2);
        if (piedziesiatka.isSelected() == true) {
            slowo = slowo.concat("(7P)");
            System.out.println(slowo);
            jTable1.setValueAt(slowo, tura, gracz * 2 - 2);
        }
        jTable1.setValueAt(punkty, tura, gracz * 2 - 1);
        int biezaca_suma = Integer.parseInt(jTable1.getValueAt(tura + 1, gracz * 2 - 1).toString()) + punkty;
        jTable1.setValueAt(biezaca_suma, tura + 1, gracz * 2 - 1);
        int[] sumy = new int[4];
        for (int i = 0; i < 4; i++) {
            sumy[i] = Integer.parseInt(jTable1.getValueAt(tura + 1, i * 2 + 1).toString());
        }
        gracz++;
        if (gracz > gracze) {
            gracz = 1;
            tura++;
            String[][] baza = new String[8][jTable1.getRowCount() - 1];
            for (int i = 0; i < jTable1.getRowCount() - 1; i++) {
                baza[0][i] = jTable1.getValueAt(i, 0).toString();
                baza[1][i] = jTable1.getValueAt(i, 1).toString();
                baza[2][i] = jTable1.getValueAt(i, 2).toString();
                baza[3][i] = jTable1.getValueAt(i, 3).toString();
                baza[4][i] = jTable1.getValueAt(i, 4).toString();
                baza[5][i] = jTable1.getValueAt(i, 5).toString();
                baza[6][i] = jTable1.getValueAt(i, 6).toString();
                baza[7][i] = jTable1.getValueAt(i, 7).toString();
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{"", "", "", "", "", "", "", ""});

            jTable1.setValueAt("", jTable1.getRowCount() - 2, 0);
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 1);
            jTable1.setValueAt("", jTable1.getRowCount() - 2, 2);
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 3);
            if (gracze > 2) {
                jTable1.setValueAt("", jTable1.getRowCount() - 2, 4);
            } else {
                jTable1.setValueAt("XXX", jTable1.getRowCount() - 2, 4);
            }
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 5);
            if (gracze > 3) {
                jTable1.setValueAt("", jTable1.getRowCount() - 2, 6);
            } else {
                jTable1.setValueAt("XXX", jTable1.getRowCount() - 2, 6);
            }
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 7);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 0);
            jTable1.setValueAt(sumy[0], jTable1.getRowCount() - 1, 1);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 2);
            jTable1.setValueAt(sumy[1], jTable1.getRowCount() - 1, 3);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 4);
            jTable1.setValueAt(sumy[2], jTable1.getRowCount() - 1, 5);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 6);
            jTable1.setValueAt(sumy[3], jTable1.getRowCount() - 1, 7);
        }
        System.out.println("tura nr:" + tura);
        System.out.println("gracz nr:" + gracz);
        jButton3.setEnabled(false);
        slowo = "";
        piedziesiatka.setSelected(false);
        premia_slowna = 1;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sprawdzane = null;
        slowo = jTextField1.getText();
        if(!"".equals(jTextField1.getText())){
        String tmp = slowo.toLowerCase();
        boolean pasuje = false;
        String regex = tmp.replace("?", ".*{1}[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ]");
        System.out.println(regex);
        try {
            String workingDirectory = System.getProperty("user.dir") + File.separator;
            File plik = new File(workingDirectory, "baza.txt");
            try (BufferedReader szperacz = new BufferedReader(new InputStreamReader(new FileInputStream(plik), "UTF8"));) {
                while ((sprawdzane = szperacz.readLine()) != null) {
                    if (((tmp.toLowerCase().equals(sprawdzane)) || ((sprawdzane.matches(regex)) == true)) && (tmp.length() == sprawdzane.length())) {
                        pasuje = true;
                        System.out.println(sprawdzane);
                        break;
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(scrabble_punkty.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText("SPRAWDZANE SŁOWO");
        jLabel4.setText((String.valueOf(slowo.toUpperCase())));
        jLabel7.setText(String.valueOf("..."));
        jLabel6.setText("...");
        if (tmp.equals(sprawdzane) || pasuje == true) {
            jButton1.setEnabled(true);
            jLabel2.setText("Słowo jest dopuszczalne");
        } else {
            jButton1.setEnabled(false);
            jButton3.setEnabled(false);
            jLabel2.setText("Słowo nie jest dopuszczalne");
        }
        pasuje = false;
        }else{
            jButton1.setEnabled(true);
            jButton3.setEnabled(true);
            jLabel4.setText("");
            jLabel2.setText("Brak słowa");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        punkty = 0;
        jTable1.setValueAt(("The End"), tura, gracz * 2 - 2);
        slowo = jTextField1.getText();
        for (int i = 0; i < slowo.length(); i++) {
            litera = slowo.charAt(i);
            System.out.println(litera);
            System.out.println(i);
            switch (litera) {
                case 'a':
                punkty = punkty + 1;
                break;
                case 'ą':
                punkty = punkty + 5;
                break;
                case 'b':
                punkty = punkty + 3;
                break;
                case 'c':
                punkty = punkty + 2;
                break;
                case 'ć':
                punkty = punkty + 6;
                break;
                case 'd':
                punkty = punkty + 2;
                break;
                case 'e':
                punkty = punkty + 1;
                break;
                case 'ę':
                punkty = punkty + 5;
                break;
                case 'f':
                punkty = punkty + 5;
                break;
                case 'g':
                punkty = punkty + 3;
                break;
                case 'h':
                punkty = punkty + 3;
                break;
                case 'i':
                punkty = punkty + 1;
                break;
                case 'j':
                punkty = punkty + 3;
                break;
                case 'k':
                punkty = punkty + 2;
                break;
                case 'l':
                punkty = punkty + 2;
                break;
                case 'ł':
                punkty = punkty + 3;
                break;
                case 'm':
                punkty = punkty + 2;
                break;
                case 'n':
                punkty = punkty + 1;
                break;
                case 'ń':
                punkty = punkty + 7;
                break;
                case 'o':
                punkty = punkty + 1;
                break;
                case 'ó':
                punkty = punkty + 5;
                break;
                case 'p':
                punkty = punkty + 2;
                break;
                case 'r':
                punkty = punkty + 1;
                break;
                case 's':
                punkty = punkty + 1;
                break;
                case 'ś':
                punkty = punkty + 5;
                break;
                case 't':
                punkty = punkty + 2;
                break;
                case 'u':
                punkty = punkty + 3;
                break;
                case 'w':
                punkty = punkty + 1;
                break;
                case 'y':
                punkty = punkty + 2;
                break;
                case 'z':
                punkty = punkty + 1;
                break;
                case 'ź':
                punkty = punkty + 9;
                break;
                case 'ż':
                punkty = punkty + 5;
                break;
            }
        }
        jTable1.setValueAt(punkty, tura, gracz * 2 - 1);
        int biezaca_suma = Integer.parseInt(jTable1.getValueAt(tura + 1, gracz * 2 - 1).toString()) - punkty;
        jTable1.setValueAt(biezaca_suma, tura + 1, gracz * 2 - 1);
        int[] sumy = new int[4];
        for (int i = 0; i < 4; i++) {
            sumy[i] = Integer.parseInt(jTable1.getValueAt(tura + 1, i * 2 + 1).toString());
        }
        gracz++;
        if (gracz > gracze) {
            gracz = 1;
            tura++;
            String[][] baza = new String[8][jTable1.getRowCount() - 1];
            for (int i = 0; i < jTable1.getRowCount() - 1; i++) {
                baza[0][i] = jTable1.getValueAt(i, 0).toString();
                baza[1][i] = jTable1.getValueAt(i, 1).toString();
                baza[2][i] = jTable1.getValueAt(i, 2).toString();
                baza[3][i] = jTable1.getValueAt(i, 3).toString();
                baza[4][i] = jTable1.getValueAt(i, 4).toString();
                baza[5][i] = jTable1.getValueAt(i, 5).toString();
                baza[6][i] = jTable1.getValueAt(i, 6).toString();
                baza[7][i] = jTable1.getValueAt(i, 7).toString();
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{"", "", "", "", "", "", "", ""});

            jTable1.setValueAt("", jTable1.getRowCount() - 2, 0);
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 1);
            jTable1.setValueAt("", jTable1.getRowCount() - 2, 2);
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 3);
            if (gracze > 2) {
                jTable1.setValueAt("", jTable1.getRowCount() - 2, 4);
            } else {
                jTable1.setValueAt("XXX", jTable1.getRowCount() - 2, 4);
            }
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 5);
            if (gracze > 3) {
                jTable1.setValueAt("", jTable1.getRowCount() - 2, 6);
            } else {
                jTable1.setValueAt("XXX", jTable1.getRowCount() - 2, 6);
            }
            jTable1.setValueAt(0, jTable1.getRowCount() - 2, 7);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 0);
            jTable1.setValueAt(sumy[0], jTable1.getRowCount() - 1, 1);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 2);
            jTable1.setValueAt(sumy[1], jTable1.getRowCount() - 1, 3);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 4);
            jTable1.setValueAt(sumy[2], jTable1.getRowCount() - 1, 5);
            jTable1.setValueAt("suma punktów:", jTable1.getRowCount() - 1, 6);
            jTable1.setValueAt(sumy[3], jTable1.getRowCount() - 1, 7);
        }
        System.out.println("tura nr:" + tura);
        System.out.println("gracz nr:" + gracz);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scrabble_punkty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new scrabble_punkty().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton dodawanieG;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox piedziesiatka;
    private javax.swing.JButton usuwanieG;
    // End of variables declaration//GEN-END:variables
}
